version: '3.11'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2309
  redis:
    image: "redis"
  celery:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - web
      - redis
  celery-beat:
    build: .
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - web
      - redis
