# Generated by Django 5.0.2 on 2024-02-10 07:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('http', '0002_user_phone'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
