# Generated by Django 5.0.2 on 2024-02-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('http', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                (
                'code', models.CharField(blank=True, max_length=8, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
