# Generated by Django 5.0.2 on 2024-02-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('http', '0007_smsconfirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendinguser',
            name='code',
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='first_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smsconfirm',
            name='resend_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='smsconfirm',
            name='try_count',
            field=models.IntegerField(default=0),
        ),
    ]
