# Generated by Django 5.0.2 on 2024-02-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('http', '0009_frontendtranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendtranslation',
            name='value_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='frontendtranslation',
            name='value_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='frontendtranslation',
            name='value_uz',
            field=models.TextField(null=True),
        ),
    ]
